# Generated by Django 3.2.7 on 2021-10-08 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=200)),
                ('question_body', models.CharField(max_length=250)),
                ('question_img', models.ImageField(blank=True, null=True, upload_to='uploaded_imgages/')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('for_game', models.CharField(max_length=100)),
                ('question_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FAQPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_title', models.CharField(max_length=100)),
                ('faq_body', models.TextField(max_length=250)),
                ('faq_img', models.ImageField(blank=True, null=True, upload_to='uploaded_imgages/')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('for_game', models.CharField(max_length=100)),
                ('faq_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_body', models.CharField(max_length=250)),
                ('post_img', models.ImageField(blank=True, null=True, upload_to='uploaded_imgages/')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('for_game', models.CharField(max_length=100)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_body', models.TextField(max_length=200)),
                ('answer_img', models.ImageField(blank=True, null=True, upload_to='uploaded_imgages/')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('answer_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.questionpost')),
            ],
        ),
    ]
