# Generated by Django 3.2.7 on 2021-10-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerpost',
            name='answer_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_imgages/'),
        ),
        migrations.AlterField(
            model_name='questionpost',
            name='question_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_imgages/'),
        ),
        migrations.AlterField(
            model_name='walkthroughcomment',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_imgages/'),
        ),
        migrations.AlterField(
            model_name='walkthroughpost',
            name='walkthrough_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_imgages/'),
        ),
    ]
