# Generated by Django 3.2.7 on 2021-10-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('game_slug', models.CharField(max_length=100)),
                ('game_release', models.DateTimeField()),
                ('game_img', models.ImageField(upload_to='')),
                ('game_desc', models.CharField(max_length=400)),
                ('esrb_rating', models.CharField(max_length=10)),
                ('platform', models.CharField(max_length=100)),
            ],
        ),
    ]
